### ISSUE TITLE
There seems to be no DOCTYPE! declaration

### ISSUE THREAD

**Issue by markitgeit** [frappe/builder#168]
The javascripts I created with JQuery and the CSS scripts I created are not applied properly. It seems that there's no DOCTYPE! declaration in the pages I'm building. Because of this, there are margins and unexpected layout issues in the page. Please take a look: 

![image](https://github.com/frappe/builder/assets/168828183/dea73746-5374-41d1-8465-f46d53677a99)

**Comment by batonac** [comment]
Builder does not include jQuery. If you want to code everything yourself, perhaps you should just use [portal pages](https://frappeframework.com/docs/user/en/portal-pages) instead of builder.

**Comment by surajshetty3416** [comment]
@markitgeit the declaration you mentioned that is missing is literally the first line.
<img width="252" alt="Screenshot 2024-06-06 at 6 07 50 PM" src="https://github.com/frappe/builder/assets/13928957/3137cdeb-5bd4-4df0-a1d0-2914a5653c4e">

Maybe your issue is related to something else? Please update your builder instance and try again.

It'll also be helpful if you can share error in your browser console and the editor view of your page to investigate further.

**Comment by surajshetty3416** [comment]
Please reopen with the requested information if you continue to face the issue.
