### ISSUE TITLE
Issue: Make preview images of builder pages private and only store latest version

### ISSUE THREAD

**Issue by the3dfox** [frappe/builder#174]
I noticed, that the preview images of the builder pages are public by default. Since the images are only used in the builder app itself, having them private might be the better implementation.

Also multiple versions of the preview images are stored which eventually will spam the file system, so having only the latest preview of the page would be desirable

**Comment by surajshetty3416** [comment]
> Also multiple versions of the preview images are stored which eventually will spam the file system, so having only the latest preview of the page would be desirable

@the3dfox thanks for pointing this. I was always under the impression that I was cleaning up old previews [with this code](https://github.com/frappe/builder/blob/747c72abe3a5b73c3c06fae5dbe11f0f09e0202c/builder/builder/doctype/builder_page/builder_page.py#L238)... but turns out it was only removing the attachment file doc and not the actual file because of the absence of `contenthash` in the doc 🗿 

This was obviously bad so I [refactored preview related code](https://github.com/frappe/builder/commit/f6996e2ee94e7b5669bcc100c7a9be2076d73902) to handle it in much simpler way. And it creates no additional preview image file hence requires no cleaning up.

---
> I noticed, that the preview images of the builder pages are public by default. Since the images are only used in the builder app itself, having them private might be the better implementation.

About this, since we are using preview as fallback meta image we can't keep preview private as of now... might change later.
