### ISSUE TITLE
Dropdown is not showing and Client script for dropdown is not working

### ISSUE THREAD

**Issue by rnd-nguyenth** [frappe/builder#258]
Hi there, I have followed the instructions from https://www.youtube.com/watch?v=4nBPhNEleWg&t=1082s but my dropdown is not showing as expected. Not sure what I am missing or this is changed since it been 7 months from the released video.

https://github.com/user-attachments/assets/122918d4-312c-4541-815d-46f6de826fd0

![image](https://github.com/user-attachments/assets/19993bb4-b554-44be-aa69-6f072c6365ac)

Please check

**Comment by surajshetty3416** [comment]
@rnd-nguyenth This issue might be because of "overflow-y: hidden" in the parent container of the dropdown... you can try and set it to "Auto" or "Visible"
<img width="276" alt="Screenshot 2024-12-05 at 9 59 32 AM" src="https://github.com/user-attachments/assets/17ce47f6-2829-4231-a6ce-8618c9fdf685">

**Comment by rnd-nguyenth** [comment]
Hi @surajshetty3416 , thanks for your reply. I applied Overflow-Y to visible but it doesn't work.

https://github.com/user-attachments/assets/de5cb7f4-cb1d-4bfe-bcfb-5000eaaac14d

**Comment by surajshetty3416** [comment]
Try making it visible in the nav container?

**Comment by rnd-nguyenth** [comment]
Yes, that's cause it is not showing. Everything works. Thanks
